// <auto-generated />
using System;
using System.Collections.Generic;
using Febris.UserNode.DataAccessLayer.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Febris.UserNode.DataAccessLayer.Migrations.XApiDb
{
    [DbContext(typeof(XApiDbContext))]
    [Migration("20260810222153_ResultSuccessCompletionNullable")]
    partial class ResultSuccessCompletionNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Febris.ModelLibrary.Models.XApiModels.Account", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("HomePage")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.HasKey("Id");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("Febris.ModelLibrary.Models.XApiModels.Actor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ContextId")
                        .HasColumnType("bigint");

                    b.Property<string>("Mbox")
                        .HasColumnType("text");

                    b.Property<string>("Mbox_sha1sum")
                        .HasColumnType("text");

                    b.Property<long?>("MemberId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("ObjectType")
                        .HasColumnType("text");

                    b.Property<string>("OpenId")
                        .HasColumnType("text");

                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("ContextId");

                    b.HasIndex("MemberId");

                    b.ToTable("Actor");
                });

            modelBuilder.Entity("Febris.ModelLibrary.Models.XApiModels.Attachment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ContentType")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("jsonb");

                    b.Property<string>("Display")
                        .HasColumnType("jsonb");

                    b.Property<string>("FileURL")
                        .HasColumnType("text");

                    b.Property<int>("Length")
                        .HasColumnType("integer");

                    b.Property<long?>("LocalStatementId")
                        .HasColumnType("bigint");

                    b.Property<string>("Sha2")
                        .HasColumnType("text");

                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("UsageType")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LocalStatementId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("Febris.ModelLibrary.Models.XApiModels.Authority", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("ActorId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.ToTable("Authority");
                });

            modelBuilder.Entity("Febris.ModelLibrary.Models.XApiModels.Context", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("ContextActivitiesId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ExtensionsId")
                        .HasColumnType("bigint");

                    b.Property<long?>("InstructorId")
                        .HasColumnType("bigint");

                    b.Property<string>("Language")
                        .HasColumnType("text");

                    b.Property<string>("Platform")
                        .HasColumnType("text");

                    b.Property<Guid>("Registration")
                        .HasColumnType("uuid");

                    b.Property<string>("Revision")
                        .HasColumnType("text");

                    b.Property<long?>("StatementReferenceKey")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.HasKey("Id");

                    b.HasIndex("ContextActivitiesId");

                    b.HasIndex("ExtensionsId");

                    b.HasIndex("InstructorId");

                    b.HasIndex("StatementReferenceKey");

                    b.ToTable("Context");
                });

            modelBuilder.Entity("Febris.ModelLibrary.Models.XApiModels.ContextActivities", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("Grouping")
                        .HasColumnType("text");

                    b.Property<string>("Other")
                        .HasColumnType("text");

                    b.Property<string>("Parent")
                        .HasColumnType("text");

                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.HasKey("Id");

                    b.ToTable("ContextActivities");
                });

            modelBuilder.Entity("Febris.ModelLibrary.Models.XApiModels.Definition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CorrectResponsesPattern")
                        .HasColumnType("jsonb");

                    b.Property<string>("Description")
                        .HasColumnType("jsonb");

                    b.Property<long?>("ExtensionsId")
                        .HasColumnType("bigint");

                    b.Property<string>("InteractionComponents")
                        .HasColumnType("text");

                    b.Property<string>("InteractionType")
                        .HasColumnType("text");

                    b.Property<string>("MoreInfo")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("jsonb");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.Property<Guid>("UUID")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExtensionsId");

                    b.ToTable("Definition");
                });

            modelBuilder.Entity("Febris.ModelLibrary.Models.XApiModels.Extensions", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ExtensionMap")
                        .HasColumnType("text");

                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.HasKey("Id");

                    b.ToTable("Extensions");
                });

            modelBuilder.Entity("Febris.ModelLibrary.Models.XApiModels.ExtraModels.XApiResultExtras", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<List<string>>("NotesList")
                        .HasColumnType("text[]");

                    b.Property<int>("RestartCount")
                        .HasColumnType("integer");

                    b.Property<long?>("ResultId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ResultUUID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.HasKey("Id");

                    b.HasIndex("ResultId");

                    b.ToTable("XApiResultExtras");
                });

            modelBuilder.Entity("Febris.ModelLibrary.Models.XApiModels.Member", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.HasKey("Id");

                    b.ToTable("Member");
                });

            modelBuilder.Entity("Febris.ModelLibrary.Models.XApiModels.ModifiedForSharing.LocalStatement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ActorId")
                        .HasColumnType("bigint");

                    b.Property<long?>("AuthorityId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ContextId")
                        .HasColumnType("bigint");

                    b.Property<long>("ObjectId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ObjectUUID")
                        .HasColumnType("uuid");

                    b.Property<long?>("ResultId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Stored")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<long>("VerbId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("VerbUUID")
                        .HasColumnType("uuid");

                    b.Property<long>("VersionId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("VersionUUID")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("AuthorityId");

                    b.HasIndex("ContextId");

                    b.HasIndex("ResultId");

                    b.HasIndex("UUID");

                    b.ToTable("LocalStatement");
                });

            modelBuilder.Entity("Febris.ModelLibrary.Models.XApiModels.Object", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Key"));

                    b.Property<long?>("DefinitionId")
                        .HasColumnType("bigint");

                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ObjectType")
                        .HasColumnType("text");

                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.HasKey("Key");

                    b.HasIndex("DefinitionId");

                    b.ToTable("Object");
                });

            modelBuilder.Entity("Febris.ModelLibrary.Models.XApiModels.Result", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool?>("Completion")
                        .HasColumnType("boolean");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<long?>("ExtensionsId")
                        .HasColumnType("bigint");

                    b.Property<string>("Response")
                        .HasColumnType("text");

                    b.Property<long?>("ScoreId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("Success")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.HasKey("Id");

                    b.HasIndex("ExtensionsId");

                    b.HasIndex("ScoreId");

                    b.ToTable("Result");
                });

            modelBuilder.Entity("Febris.ModelLibrary.Models.XApiModels.Score", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<float>("Max")
                        .HasColumnType("real");

                    b.Property<float>("Min")
                        .HasColumnType("real");

                    b.Property<float>("Raw")
                        .HasColumnType("real");

                    b.Property<float>("Scaled")
                        .HasColumnType("real");

                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.HasKey("Id");

                    b.ToTable("Score");
                });

            modelBuilder.Entity("Febris.ModelLibrary.Models.XApiModels.StatementReference", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Key"));

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ObjectType")
                        .HasColumnType("text");

                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.HasKey("Key");

                    b.ToTable("StatementReference");
                });

            modelBuilder.Entity("Febris.ModelLibrary.Models.XApiModels.Verb", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Key"));

                    b.Property<string>("Display")
                        .HasColumnType("jsonb");

                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.HasKey("Key");

                    b.ToTable("Verb");
                });

            modelBuilder.Entity("Febris.ModelLibrary.Models.XApiModels.Version", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("VersionNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Version");
                });

            modelBuilder.Entity("Febris.ModelLibrary.Models.XApiModels.Actor", b =>
                {
                    b.HasOne("Febris.ModelLibrary.Models.XApiModels.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId");

                    b.HasOne("Febris.ModelLibrary.Models.XApiModels.Context", null)
                        .WithMany("Group")
                        .HasForeignKey("ContextId");

                    b.HasOne("Febris.ModelLibrary.Models.XApiModels.Member", "Member")
                        .WithMany("Actors")
                        .HasForeignKey("MemberId");

                    b.Navigation("Account");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Febris.ModelLibrary.Models.XApiModels.Attachment", b =>
                {
                    b.HasOne("Febris.ModelLibrary.Models.XApiModels.ModifiedForSharing.LocalStatement", null)
                        .WithMany("Attachments")
                        .HasForeignKey("LocalStatementId");
                });

            modelBuilder.Entity("Febris.ModelLibrary.Models.XApiModels.Authority", b =>
                {
                    b.HasOne("Febris.ModelLibrary.Models.XApiModels.Actor", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId");

                    b.Navigation("Actor");
                });

            modelBuilder.Entity("Febris.ModelLibrary.Models.XApiModels.Context", b =>
                {
                    b.HasOne("Febris.ModelLibrary.Models.XApiModels.ContextActivities", "ContextActivities")
                        .WithMany()
                        .HasForeignKey("ContextActivitiesId");

                    b.HasOne("Febris.ModelLibrary.Models.XApiModels.Extensions", "Extensions")
                        .WithMany()
                        .HasForeignKey("ExtensionsId");

                    b.HasOne("Febris.ModelLibrary.Models.XApiModels.Actor", "Instructor")
                        .WithMany()
                        .HasForeignKey("InstructorId");

                    b.HasOne("Febris.ModelLibrary.Models.XApiModels.StatementReference", "StatementReference")
                        .WithMany()
                        .HasForeignKey("StatementReferenceKey");

                    b.Navigation("ContextActivities");

                    b.Navigation("Extensions");

                    b.Navigation("Instructor");

                    b.Navigation("StatementReference");
                });

            modelBuilder.Entity("Febris.ModelLibrary.Models.XApiModels.Definition", b =>
                {
                    b.HasOne("Febris.ModelLibrary.Models.XApiModels.Extensions", "Extensions")
                        .WithMany()
                        .HasForeignKey("ExtensionsId");

                    b.Navigation("Extensions");
                });

            modelBuilder.Entity("Febris.ModelLibrary.Models.XApiModels.ExtraModels.XApiResultExtras", b =>
                {
                    b.HasOne("Febris.ModelLibrary.Models.XApiModels.Result", "Result")
                        .WithMany()
                        .HasForeignKey("ResultId");

                    b.Navigation("Result");
                });

            modelBuilder.Entity("Febris.ModelLibrary.Models.XApiModels.ModifiedForSharing.LocalStatement", b =>
                {
                    b.HasOne("Febris.ModelLibrary.Models.XApiModels.Actor", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Febris.ModelLibrary.Models.XApiModels.Authority", "Authority")
                        .WithMany()
                        .HasForeignKey("AuthorityId");

                    b.HasOne("Febris.ModelLibrary.Models.XApiModels.Context", "Context")
                        .WithMany()
                        .HasForeignKey("ContextId");

                    b.HasOne("Febris.ModelLibrary.Models.XApiModels.Result", "Result")
                        .WithMany()
                        .HasForeignKey("ResultId");

                    b.Navigation("Actor");

                    b.Navigation("Authority");

                    b.Navigation("Context");

                    b.Navigation("Result");
                });

            modelBuilder.Entity("Febris.ModelLibrary.Models.XApiModels.Object", b =>
                {
                    b.HasOne("Febris.ModelLibrary.Models.XApiModels.Definition", "Definition")
                        .WithMany()
                        .HasForeignKey("DefinitionId");

                    b.Navigation("Definition");
                });

            modelBuilder.Entity("Febris.ModelLibrary.Models.XApiModels.Result", b =>
                {
                    b.HasOne("Febris.ModelLibrary.Models.XApiModels.Extensions", "Extensions")
                        .WithMany()
                        .HasForeignKey("ExtensionsId");

                    b.HasOne("Febris.ModelLibrary.Models.XApiModels.Score", "Score")
                        .WithMany()
                        .HasForeignKey("ScoreId");

                    b.Navigation("Extensions");

                    b.Navigation("Score");
                });

            modelBuilder.Entity("Febris.ModelLibrary.Models.XApiModels.Context", b =>
                {
                    b.Navigation("Group");
                });

            modelBuilder.Entity("Febris.ModelLibrary.Models.XApiModels.Member", b =>
                {
                    b.Navigation("Actors");
                });

            modelBuilder.Entity("Febris.ModelLibrary.Models.XApiModels.ModifiedForSharing.LocalStatement", b =>
                {
                    b.Navigation("Attachments");
                });
#pragma warning restore 612, 618
        }
    }
}
