#!/usr/bin/env bash
# Febris Node -- write a ready-to-run .env for the clone-and-run compose stack.
# Idempotent-safe: refuses to overwrite an existing .env unless called with --force,
# so re-running can never silently rotate the secrets a provisioned stack already
# depends on (the DB password in the pgdata volume, the JWT secret devices hold
# refresh tokens against).
#
# Usage:  ./selfhost/generate-env.sh [--force]
set -euo pipefail

cd "$(dirname "$0")/.."

if [[ -f .env && "${1:-}" != "--force" ]]; then
    echo "error: .env already exists. Re-run with --force to overwrite it." >&2
    echo "       (Overwriting rotates POSTGRES_PASSWORD/NODE_JWT_SECRET, which a" >&2
    echo "       provisioned stack's volumes and issued tokens still depend on.)" >&2
    exit 1
fi

if ! command -v openssl >/dev/null 2>&1; then
    echo "error: openssl is required to generate secrets." >&2
    exit 1
fi

postgres_password="$(openssl rand -hex 24)"
node_jwt_secret="$(openssl rand -hex 32)"
# Must satisfy the portal's Identity password policy (upper + lower + digit, symbol
# optional, length >= 8): fixed 'Fb1!' class-cover prefix + random hex tail.
node_admin_password="Fb1!$(openssl rand -hex 10)"

cat > .env <<EOF
# Generated by selfhost/generate-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Knob documentation lives in .env.example. This file is git-ignored -- never commit it.

POSTGRES_PASSWORD=${postgres_password}
NODE_JWT_SECRET=${node_jwt_secret}

NODE_ADMIN_EMAIL=admin@febris.localhost
NODE_ADMIN_PASSWORD=${node_admin_password}

NODE_HTTPS_PORT=8443
NODE_API_HTTP_PORT=8081
# Loopback by default: the plain-HTTP API would otherwise send device tokens and the hardware
# credential across the LAN in clear. Set 0.0.0.0 only if a device cannot trust the local CA.
NODE_API_HTTP_BIND=127.0.0.1

NODE_AUTO_PROVISION_JIT=false

SMTP_HOST=
SMTP_PORT=587
SMTP_SENDER=
SMTP_PASSWORD=
EOF
chmod 600 .env

echo "Wrote .env with fresh local secrets."
echo
echo "  Portal:      https://febris.localhost:8443   (after: docker compose up -d --build)"
echo "  First login: admin@febris.localhost / ${node_admin_password}"
echo
echo "The password is stored in .env (chmod 600). Change it after first login."
