// <auto-generated />
using System;
using System.Collections.Generic;
using Febris.UserNode.DataAccessLayer.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Febris.UserNode.DataAccessLayer.Migrations.DataDb
{
    [DbContext(typeof(DataDbContext))]
    [Migration("20260805130000_ParentLinkedStudentTable")]
    partial class ParentLinkedStudentTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Febris.ModelLibrary.LookupModels.CohortLinkedCurriculum", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CohortId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("CohortUUID")
                        .HasColumnType("uuid");

                    b.Property<long?>("CurriculumId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("CurriculumUUID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastUpdateTimeStamp")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("TimeStamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.HasKey("Id");

                    b.HasIndex("CohortId");

                    b.HasIndex("CurriculumId");

                    b.ToTable("CohortLinkedCurriculum", (string)null);
                });

            modelBuilder.Entity("Febris.ModelLibrary.Models.DataModels.ParentLinkedStudent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("LastUpdateTimeStamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ParentUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudentActorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudentUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UUID")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentUserId");

                    b.HasIndex("StudentActorId");

                    b.ToTable("ParentLinkedStudent", (string)null);
                });

            modelBuilder.Entity("Febris.ModelLibrary.LookupModels.ModuleLinkedCurriculum", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CurriculumId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("CurriculumUUID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastUpdateTimeStamp")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long?>("ModuleId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ModuleUUID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("TimeStamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.HasKey("Id");

                    b.HasIndex("CurriculumId");

                    b.HasIndex("ModuleId");

                    b.ToTable("ModuleLinkedCurriculum", (string)null);
                });

            modelBuilder.Entity("Febris.ModelLibrary.LookupModels.CohortLinkedLocation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CohortId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("CohortUUID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastUpdateTimeStamp")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long?>("LocationId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LocationUUID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("TimeStamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.HasKey("Id");

                    b.HasIndex("CohortId");

                    b.HasIndex("LocationId");

                    b.ToTable("CohortLinkedLocation", (string)null);
                });

            modelBuilder.Entity("Febris.ModelLibrary.LookupModels.HardwareLinkedCohort", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CohortId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("CohortUUID")
                        .HasColumnType("uuid");

                    b.Property<long>("HardwareId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("HardwareUUID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastUpdateTimeStamp")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("TimeStamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.HasKey("Id");

                    b.HasIndex("CohortId");

                    b.HasIndex("HardwareId");

                    b.ToTable("HardwareLinkedCohort", (string)null);
                });

            modelBuilder.Entity("Febris.ModelLibrary.LookupModels.HardwareLinkedCurriculum", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CurriculumId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("CurriculumUUID")
                        .HasColumnType("uuid");

                    b.Property<long>("HardwareId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("HardwareUUID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastUpdateTimeStamp")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("TimeStamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.HasKey("Id");

                    b.HasIndex("CurriculumId");

                    b.HasIndex("HardwareId");

                    b.ToTable("HardwareLinkedCurriculum", (string)null);
                });

            modelBuilder.Entity("Febris.ModelLibrary.LookupModels.LocalHardwareLinkedModule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("HardwareId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("HardwareUUID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastUpdateTimeStamp")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("ModuleId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ModuleUUID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("TimeStamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.HasKey("Id");

                    b.HasIndex("HardwareId");

                    b.ToTable("HardwareLinkedModule", (string)null);
                });

            modelBuilder.Entity("Febris.ModelLibrary.LookupModels.LocalMicrocredentialLinkedActor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ActorId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ActorUUID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastUpdateTimeStamp")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("MicrocredentialId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("MicrocredentialUUID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("TimeStamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime?>("ValidityExparationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("ValidityExpires")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("LocalMicrocredentialLinkedActor", (string)null);
                });

            modelBuilder.Entity("Febris.ModelLibrary.LookupModels.LocationLinkedHardware", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("HardwareId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("HardwareUUID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastUpdateTimeStamp")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long?>("LocationId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LocationUUID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("TimeStamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.HasKey("Id");

                    b.HasIndex("HardwareId");

                    b.HasIndex("LocationId");

                    b.ToTable("LocationLinkedHardware", (string)null);
                });

            modelBuilder.Entity("Febris.ModelLibrary.LookupModels.LocationLinkedUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AttachmentStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdateTimeStamp")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long?>("LocationId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LocationUUID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("TimeStamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("LocationLinkedUser", (string)null);
                });

            modelBuilder.Entity("Febris.ModelLibrary.LookupModels.ModuleLinkedObject", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("LastUpdateTimeStamp")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long?>("ModuleId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ModuleUUID")
                        .HasColumnType("uuid");

                    b.Property<long>("ObjectId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ObjectUUID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("TimeStamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.ToTable("ModuleLinkedObject", (string)null);
                });

            modelBuilder.Entity("Febris.ModelLibrary.Models.DataModels.AccreditationBody", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AccreditationBodySettingsId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("AccreditationBodySettingsUUID")
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<bool>("IsLockedOut")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdateTimeStamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<int>("MaxTestUserAccounts")
                        .HasColumnType("integer");

                    b.Property<int>("MaxVideoStorage")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UUID")
                        .HasColumnType("uuid");

                    b.Property<string>("ZipCode")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AccreditationBodySettingsId");

                    b.ToTable("AccreditationBody", (string)null);
                });

            modelBuilder.Entity("Febris.ModelLibrary.Models.DataModels.AccreditationBodySettings", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("AllowEmailAddressesOutsideOfDomain")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("EmailDomain")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<bool>("ForceMultifactorAuthentication")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdateTimeStamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Logo")
                        .HasColumnType("text");

                    b.Property<string>("POCEmail")
                        .HasColumnType("text");

                    b.Property<string>("POCPhoneNumber")
                        .HasColumnType("text");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UUID")
                        .HasColumnType("uuid");

                    b.Property<string>("Website")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AccreditationBodySettings", (string)null);
                });

            modelBuilder.Entity("Febris.ModelLibrary.Models.DataModels.Cohort", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Archive")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("InstructorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastUpdateTimeStamp")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("LockMembers")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime>("TimeStamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.HasKey("Id");

                    b.ToTable("Cohort", (string)null);
                });

            modelBuilder.Entity("Febris.ModelLibrary.Models.DataModels.CohortMember", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CohortId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("CohortUUID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastUpdateTimeStamp")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("TimeStamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CohortId");

                    b.ToTable("CohortMember", (string)null);
                });

            modelBuilder.Entity("Febris.ModelLibrary.Models.DataModels.ContentDeveloper", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("ConnectionToken")
                        .HasColumnType("text");

                    b.Property<long?>("ContentDeveloperSettingsId")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("ContentDeveloperSettingsUUID")
                        .HasColumnType("uuid");

                    b.Property<long?>("ContentDeveloperTypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<bool>("IsLockedOut")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdateTimeStamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<int>("MaxTestUserAccounts")
                        .HasColumnType("integer");

                    b.Property<int>("MaxVideoStorage")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<bool>("PaymentInfoVerified")
                        .HasColumnType("boolean");

                    b.Property<decimal>("ServiceChargeRate")
                        .HasColumnType("numeric");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UUID")
                        .HasColumnType("uuid");

                    b.Property<string>("ZipCode")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ContentDeveloperSettingsId");

                    b.HasIndex("ContentDeveloperTypeId");

                    b.ToTable("ContentDeveloper", (string)null);
                });

            modelBuilder.Entity("Febris.ModelLibrary.Models.DataModels.ContentDeveloperSettings", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("AllowEmailAddressesOutsideOfDomain")
                        .HasColumnType("boolean");

                    b.Property<bool>("ApplyDiscountToEntireProductRange")
                        .HasColumnType("boolean");

                    b.Property<bool>("AutoConnectAllLibraryCurriculum")
                        .HasColumnType("boolean");

                    b.Property<bool>("AutoDownloadLibraryAcrossHardware")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("EmailDomain")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<bool>("ForceMultifactorAuthentication")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdateTimeStamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Logo")
                        .HasColumnType("text");

                    b.Property<string>("POCEmail")
                        .HasColumnType("text");

                    b.Property<string>("POCPhoneNumber")
                        .HasColumnType("text");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UUID")
                        .HasColumnType("uuid");

                    b.Property<string>("Website")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ContentDeveloperSettings", (string)null);
                });

            modelBuilder.Entity("Febris.ModelLibrary.Models.DataModels.ContentDeveloperType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdateTimeStamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UUID")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("ContentDeveloperType", (string)null);
                });

            modelBuilder.Entity("Febris.ModelLibrary.Models.DataModels.Curriculum", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CurriculumClassificationId")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("CurriculumClassificationUUID")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdateTimeStamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("MicroCredentialAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<bool>("Obsolete")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UUID")
                        .HasColumnType("uuid");

                    b.Property<string>("Version")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CurriculumClassificationId");

                    b.ToTable("Curriculum", (string)null);
                });

            modelBuilder.Entity("Febris.ModelLibrary.Models.DataModels.CurriculumClassification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdateTimeStamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<bool>("Obsolete")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UUID")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("CurriculumClassification", (string)null);
                });

            modelBuilder.Entity("Febris.ModelLibrary.Models.DataModels.DeploymentType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdateTimeStamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UUID")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("DeploymentType", (string)null);
                });

            modelBuilder.Entity("Febris.ModelLibrary.Models.DataModels.Hardware", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DescriptiveName")
                        .HasColumnType("text");

                    b.Property<int>("HardwareCondition")
                        .HasColumnType("integer");

                    b.Property<long?>("HardwareTypeId")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("HardwareTypeUUID")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsLockedOut")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdateTimeStamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PhysicalLicense")
                        .HasColumnType("text");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UUID")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("HardwareTypeId");

                    b.ToTable("Hardware1", (string)null);
                });

            modelBuilder.Entity("Febris.ModelLibrary.Models.DataModels.HardwareType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdateTimeStamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UUID")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("HardwareType", (string)null);
                });

            modelBuilder.Entity("Febris.ModelLibrary.Models.DataModels.HubFederationConfig", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AuthenticationApi")
                        .HasColumnType("text");

                    b.Property<string>("DataApi")
                        .HasColumnType("text");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdateTimeStamp")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("LicenseKey")
                        .HasColumnType("text");

                    b.Property<DateTime>("TimeStamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("HubFederationConfig", (string)null);
                });

            modelBuilder.Entity("Febris.ModelLibrary.Models.DataModels.Institution", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<long?>("DeploymentTypeId")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("DeploymentTypeUUID")
                        .HasColumnType("uuid");

                    b.Property<long?>("InstitutionSettingsId")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("InstitutionSettingsUUID")
                        .HasColumnType("uuid");

                    b.Property<long?>("InstitutionTypeId")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("InstitutionTypeUUID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastUpdateTimeStamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<int>("MaxTestUserAccounts")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Token")
                        .HasColumnType("text");

                    b.Property<Guid>("UUID")
                        .HasColumnType("uuid");

                    b.Property<string>("ZipCode")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DeploymentTypeId");

                    b.HasIndex("InstitutionSettingsId");

                    b.HasIndex("InstitutionTypeId");

                    b.ToTable("Institution", (string)null);
                });

            modelBuilder.Entity("Febris.ModelLibrary.Models.DataModels.InstitutionSettings", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("AllowEmailAddressesOutsideOfDomain")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowMigrations")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowPrivateDeployments")
                        .HasColumnType("boolean");

                    b.Property<bool>("AutoConnectAllLibraryCurriculum")
                        .HasColumnType("boolean");

                    b.Property<bool>("AutoDownloadLibraryAcrossHardware")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("EmailDomain")
                        .HasColumnType("text");

                    b.Property<bool>("FERPACompliance")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<bool>("ForceMultifactorAuthentication")
                        .HasColumnType("boolean");

                    b.Property<bool>("ForcePasswordValidityTimespan")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFederallyTaxExempt")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNonProfit")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsStateTaxExempt")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdateTimeStamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Logo")
                        .HasColumnType("text");

                    b.Property<int>("MaxVideoStorage")
                        .HasColumnType("integer");

                    b.Property<string>("POCEmail")
                        .HasColumnType("text");

                    b.Property<string>("POCPhoneNumber")
                        .HasColumnType("text");

                    b.Property<int>("PasswordValidityInMonths")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UUID")
                        .HasColumnType("uuid");

                    b.Property<bool>("UseMaxVideoStorage")
                        .HasColumnType("boolean");

                    b.Property<bool>("UseVideoStrorageTimeSpan")
                        .HasColumnType("boolean");

                    b.Property<bool>("VideoStorageOption")
                        .HasColumnType("boolean");

                    b.Property<int>("VideoStorageTimeSpan")
                        .HasColumnType("integer");

                    b.Property<string>("Website")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("InstitutionSettings", (string)null);
                });

            modelBuilder.Entity("Febris.ModelLibrary.Models.DataModels.InstitutionType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdateTimeStamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UUID")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("InstitutionType", (string)null);
                });

            modelBuilder.Entity("Febris.ModelLibrary.Models.DataModels.LocalHardware", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DescriptiveName")
                        .HasColumnType("text");

                    b.Property<int>("HardwareCondition")
                        .HasColumnType("integer");

                    b.Property<long>("HardwareTypeId")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("HardwareTypeUUID")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsLockedOut")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdateTimeStamp")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("PhysicalLicense")
                        .HasColumnType("text");

                    b.Property<DateTime>("TimeStamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.HasKey("Id");

                    b.ToTable("Hardware", (string)null);
                });

            modelBuilder.Entity("Febris.ModelLibrary.Models.DataModels.LocalSoftwarePackage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Language")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdateTimeStamp")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("LocalSoftwarePackageType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<bool>("Obsolete")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TimeStamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Version")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LocalSoftwarePackage", (string)null);
                });

            modelBuilder.Entity("Febris.ModelLibrary.Models.DataModels.Location", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdateTimeStamp")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<DateTime>("TimeStamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("ZipCode")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Location", (string)null);
                });

            modelBuilder.Entity("Febris.ModelLibrary.Models.DataModels.MessageBoard", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AccreditationBodyId")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("AccreditationBodyUUID")
                        .HasColumnType("uuid");

                    b.Property<bool>("Archive")
                        .HasColumnType("boolean");

                    b.Property<long?>("ContentDeveloperId")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("ContentDeveloperUUID")
                        .HasColumnType("uuid");

                    b.Property<long?>("InstitutionId")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("InstitutionUUID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastUpdateTimeStamp")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long?>("LocationId")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("LocationUUID")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .HasColumnType("text");

                    b.Property<DateTime>("TimeStamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("UserEmail")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AccreditationBodyId");

                    b.HasIndex("ContentDeveloperId");

                    b.HasIndex("InstitutionId");

                    b.HasIndex("LocationId");

                    b.ToTable("MessageBoard", (string)null);
                });

            modelBuilder.Entity("Febris.ModelLibrary.Models.DataModels.Module", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("EstimatedCompletionTime")
                        .HasColumnType("integer");

                    b.Property<string>("InteractionComponents")
                        .HasColumnType("text");

                    b.Property<int>("Language")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdateTimeStamp")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("MainSectionCount")
                        .HasColumnType("integer");

                    b.Property<long?>("ModuleClassificationId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ModuleClassificationUUID")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<bool>("Obsolete")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TimeStamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("TotalSectionCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Version")
                        .HasColumnType("text");

                    b.Property<int>("XApiInteractionType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ModuleClassificationId");

                    b.ToTable("Module", (string)null);
                });

            modelBuilder.Entity("Febris.ModelLibrary.Models.DataModels.ModuleClassification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdateTimeStamp")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<bool>("Obsolete")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TimeStamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.HasKey("Id");

                    b.ToTable("ModuleClassification", (string)null);
                });

            modelBuilder.Entity("Febris.ModelLibrary.Models.DataModels.NodeIdentity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("InstitutionUUID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastUpdateTimeStamp")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime>("TimeStamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.HasKey("Id");

                    b.ToTable("NodeIdentity", (string)null);
                });

            modelBuilder.Entity("Febris.ModelLibrary.Models.DataModels.PackageArtifact", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ContentLength")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastUpdateTimeStamp")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Sha256")
                        .HasColumnType("text");

                    b.Property<string>("SourceFileName")
                        .HasColumnType("text");

                    b.Property<string>("StorageKey")
                        .HasColumnType("text");

                    b.Property<DateTime>("TimeStamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.HasKey("Id");

                    b.HasIndex("StorageKey")
                        .IsUnique();

                    b.ToTable("PackageArtifact", (string)null);
                });

            modelBuilder.Entity("Febris.ModelLibrary.Models.DataModels.TestUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("IdentificationNumber")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdateTimeStamp")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("PhotoOfProfessional")
                        .HasColumnType("text");

                    b.Property<DateTime>("TimeStamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TestUser", (string)null);
                });

            modelBuilder.Entity("Febris.ModelLibrary.Models.XApiModels.ExtraModels.MicrocredentialProgress", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ActorId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ActorUUID")
                        .HasColumnType("uuid");

                    b.Property<bool>("Complete")
                        .HasColumnType("boolean");

                    b.Property<List<long>>("CompletedObjectIdList")
                        .HasColumnType("bigint[]");

                    b.Property<List<Guid>>("CompletedObjectUUIDList")
                        .HasColumnType("uuid[]");

                    b.Property<DateTime?>("CompletionTimeFrame")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("InProgress")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdateTimeStamp")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long?>("MicrocredentialId")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("MicrocredentialUUID")
                        .HasColumnType("uuid");

                    b.Property<List<long>>("ReferenceObjectIdList")
                        .HasColumnType("bigint[]");

                    b.Property<List<Guid>>("ReferenceObjectUUIDList")
                        .HasColumnType("uuid[]");

                    b.Property<DateTime>("TimeStamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<List<long>>("ValidStatementIdList")
                        .HasColumnType("bigint[]");

                    b.Property<List<Guid>>("ValidStatementUUIDList")
                        .HasColumnType("uuid[]");

                    b.HasKey("Id");

                    b.ToTable("MicrocredentialProgress", (string)null);
                });

            modelBuilder.Entity("Febris.ModelLibrary.LookupModels.CohortLinkedCurriculum", b =>
                {
                    b.HasOne("Febris.ModelLibrary.Models.DataModels.Cohort", "Cohort")
                        .WithMany()
                        .HasForeignKey("CohortId");

                    b.HasOne("Febris.ModelLibrary.Models.DataModels.Curriculum", "Curriculum")
                        .WithMany()
                        .HasForeignKey("CurriculumId");

                    b.Navigation("Cohort");

                    b.Navigation("Curriculum");
                });

            modelBuilder.Entity("Febris.ModelLibrary.LookupModels.ModuleLinkedCurriculum", b =>
                {
                    b.HasOne("Febris.ModelLibrary.Models.DataModels.Curriculum", "Curriculum")
                        .WithMany()
                        .HasForeignKey("CurriculumId");

                    b.HasOne("Febris.ModelLibrary.Models.DataModels.Module", "Module")
                        .WithMany()
                        .HasForeignKey("ModuleId");

                    b.Navigation("Curriculum");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("Febris.ModelLibrary.LookupModels.CohortLinkedLocation", b =>
                {
                    b.HasOne("Febris.ModelLibrary.Models.DataModels.Cohort", "Cohort")
                        .WithMany()
                        .HasForeignKey("CohortId");

                    b.HasOne("Febris.ModelLibrary.Models.DataModels.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.Navigation("Cohort");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Febris.ModelLibrary.LookupModels.HardwareLinkedCohort", b =>
                {
                    b.HasOne("Febris.ModelLibrary.Models.DataModels.Cohort", "Cohort")
                        .WithMany()
                        .HasForeignKey("CohortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Febris.ModelLibrary.Models.DataModels.LocalHardware", "Hardware")
                        .WithMany()
                        .HasForeignKey("HardwareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cohort");

                    b.Navigation("Hardware");
                });

            modelBuilder.Entity("Febris.ModelLibrary.LookupModels.HardwareLinkedCurriculum", b =>
                {
                    b.HasOne("Febris.ModelLibrary.Models.DataModels.Curriculum", "Curriculum")
                        .WithMany()
                        .HasForeignKey("CurriculumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Febris.ModelLibrary.Models.DataModels.Hardware", "Hardware")
                        .WithMany()
                        .HasForeignKey("HardwareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curriculum");

                    b.Navigation("Hardware");
                });

            modelBuilder.Entity("Febris.ModelLibrary.LookupModels.LocalHardwareLinkedModule", b =>
                {
                    b.HasOne("Febris.ModelLibrary.Models.DataModels.LocalHardware", "Hardware")
                        .WithMany()
                        .HasForeignKey("HardwareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hardware");
                });

            modelBuilder.Entity("Febris.ModelLibrary.LookupModels.LocationLinkedHardware", b =>
                {
                    b.HasOne("Febris.ModelLibrary.Models.DataModels.Hardware", "Hardware")
                        .WithMany()
                        .HasForeignKey("HardwareId");

                    b.HasOne("Febris.ModelLibrary.Models.DataModels.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.Navigation("Hardware");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Febris.ModelLibrary.LookupModels.LocationLinkedUser", b =>
                {
                    b.HasOne("Febris.ModelLibrary.Models.DataModels.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Febris.ModelLibrary.LookupModels.ModuleLinkedObject", b =>
                {
                    b.HasOne("Febris.ModelLibrary.Models.DataModels.Module", "Module")
                        .WithMany()
                        .HasForeignKey("ModuleId");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("Febris.ModelLibrary.Models.DataModels.AccreditationBody", b =>
                {
                    b.HasOne("Febris.ModelLibrary.Models.DataModels.AccreditationBodySettings", "AccreditationBodySettings")
                        .WithMany()
                        .HasForeignKey("AccreditationBodySettingsId");

                    b.Navigation("AccreditationBodySettings");
                });

            modelBuilder.Entity("Febris.ModelLibrary.Models.DataModels.CohortMember", b =>
                {
                    b.HasOne("Febris.ModelLibrary.Models.DataModels.Cohort", "Cohort")
                        .WithMany()
                        .HasForeignKey("CohortId");

                    b.Navigation("Cohort");
                });

            modelBuilder.Entity("Febris.ModelLibrary.Models.DataModels.ContentDeveloper", b =>
                {
                    b.HasOne("Febris.ModelLibrary.Models.DataModels.ContentDeveloperSettings", "ContentDeveloperSettings")
                        .WithMany()
                        .HasForeignKey("ContentDeveloperSettingsId");

                    b.HasOne("Febris.ModelLibrary.Models.DataModels.ContentDeveloperType", "ContentDeveloperType")
                        .WithMany()
                        .HasForeignKey("ContentDeveloperTypeId");

                    b.Navigation("ContentDeveloperSettings");

                    b.Navigation("ContentDeveloperType");
                });

            modelBuilder.Entity("Febris.ModelLibrary.Models.DataModels.Curriculum", b =>
                {
                    b.HasOne("Febris.ModelLibrary.Models.DataModels.CurriculumClassification", "CurriculumClassification")
                        .WithMany()
                        .HasForeignKey("CurriculumClassificationId");

                    b.Navigation("CurriculumClassification");
                });

            modelBuilder.Entity("Febris.ModelLibrary.Models.DataModels.Hardware", b =>
                {
                    b.HasOne("Febris.ModelLibrary.Models.DataModels.HardwareType", "HardwareType")
                        .WithMany()
                        .HasForeignKey("HardwareTypeId");

                    b.Navigation("HardwareType");
                });

            modelBuilder.Entity("Febris.ModelLibrary.Models.DataModels.Institution", b =>
                {
                    b.HasOne("Febris.ModelLibrary.Models.DataModels.DeploymentType", "DeploymentType")
                        .WithMany()
                        .HasForeignKey("DeploymentTypeId");

                    b.HasOne("Febris.ModelLibrary.Models.DataModels.InstitutionSettings", "InstitutionSettings")
                        .WithMany()
                        .HasForeignKey("InstitutionSettingsId");

                    b.HasOne("Febris.ModelLibrary.Models.DataModels.InstitutionType", "InstitutionType")
                        .WithMany()
                        .HasForeignKey("InstitutionTypeId");

                    b.Navigation("DeploymentType");

                    b.Navigation("InstitutionSettings");

                    b.Navigation("InstitutionType");
                });

            modelBuilder.Entity("Febris.ModelLibrary.Models.DataModels.MessageBoard", b =>
                {
                    b.HasOne("Febris.ModelLibrary.Models.DataModels.AccreditationBody", "AccreditationBody")
                        .WithMany()
                        .HasForeignKey("AccreditationBodyId");

                    b.HasOne("Febris.ModelLibrary.Models.DataModels.ContentDeveloper", "ContentDeveloper")
                        .WithMany()
                        .HasForeignKey("ContentDeveloperId");

                    b.HasOne("Febris.ModelLibrary.Models.DataModels.Institution", "Institution")
                        .WithMany()
                        .HasForeignKey("InstitutionId");

                    b.HasOne("Febris.ModelLibrary.Models.DataModels.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.Navigation("AccreditationBody");

                    b.Navigation("ContentDeveloper");

                    b.Navigation("Institution");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Febris.ModelLibrary.Models.DataModels.Module", b =>
                {
                    b.HasOne("Febris.ModelLibrary.Models.DataModels.ModuleClassification", "ModuleClassification")
                        .WithMany()
                        .HasForeignKey("ModuleClassificationId");

                    b.Navigation("ModuleClassification");
                });
#pragma warning restore 612, 618
        }
    }
}
